### ISSUE TITLE
Develop about page

### ISSUE THREAD

**Issue by RiyaMathew-11** [dscmbcet/website-3.0#3]
Create an about page with the following design: 

![Image](https://github.com/dscmbcet/website-3.0/assets/60656677/6d256650-00d0-4749-b53f-d44e9aeeb4c2)

**Comment by navaneethvenu** [comment]
@RiyaMathew-11 checking back on this

**Comment by RiyaMathew-11** [comment]
> @RiyaMathew-11 checking back on this

PR ready for review
